# Generated by Django 3.1.3 on 2020-11-28 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.newtweet')),
            ],
        ),
    ]
